# © 2021 Raoul Müller. All rights reserved.

name:    habits
version: 0.0.0+1

environment:
  sdk: '>=2.12.0-29.10.beta'

dependencies:
  bloc:        7.0.0-nullsafety.0
  device_info: 2.0.0-nullsafety.1
  flutter:
    sdk: flutter
  google_fonts: 1.1.1
  http:        0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.5.1

flutter:
  uses-material-design: true
  assets:
    - res/
